// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "C_drain_IO_L2_out.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic C_drain_IO_L2_out::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic C_drain_IO_L2_out::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> C_drain_IO_L2_out::ap_ST_fsm_state1 = "1";
const sc_lv<5> C_drain_IO_L2_out::ap_ST_fsm_state2 = "10";
const sc_lv<5> C_drain_IO_L2_out::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<5> C_drain_IO_L2_out::ap_ST_fsm_state5 = "1000";
const sc_lv<5> C_drain_IO_L2_out::ap_ST_fsm_pp1_stage0 = "10000";
const bool C_drain_IO_L2_out::ap_const_boolean_1 = true;
const sc_lv<32> C_drain_IO_L2_out::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> C_drain_IO_L2_out::ap_const_lv32_2 = "10";
const bool C_drain_IO_L2_out::ap_const_boolean_0 = false;
const sc_lv<1> C_drain_IO_L2_out::ap_const_lv1_0 = "0";
const sc_lv<32> C_drain_IO_L2_out::ap_const_lv32_4 = "100";
const sc_lv<32> C_drain_IO_L2_out::ap_const_lv32_1 = "1";
const sc_lv<32> C_drain_IO_L2_out::ap_const_lv32_3 = "11";
const sc_lv<1> C_drain_IO_L2_out::ap_const_lv1_1 = "1";
const sc_lv<6> C_drain_IO_L2_out::ap_const_lv6_0 = "000000";
const sc_lv<5> C_drain_IO_L2_out::ap_const_lv5_0 = "00000";
const sc_lv<2> C_drain_IO_L2_out::ap_const_lv2_0 = "00";
const sc_lv<6> C_drain_IO_L2_out::ap_const_lv6_20 = "100000";
const sc_lv<6> C_drain_IO_L2_out::ap_const_lv6_1 = "1";
const sc_lv<5> C_drain_IO_L2_out::ap_const_lv5_8 = "1000";
const sc_lv<2> C_drain_IO_L2_out::ap_const_lv2_2 = "10";
const sc_lv<2> C_drain_IO_L2_out::ap_const_lv2_1 = "1";
const sc_lv<5> C_drain_IO_L2_out::ap_const_lv5_1 = "1";

C_drain_IO_L2_out::C_drain_IO_L2_out(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln1043_fu_147_p2);
    sensitive << ( indvar_flatten49_reg_85 );

    SC_METHOD(thread_add_ln1044_fu_214_p2);
    sensitive << ( indvar_flatten37_reg_96 );

    SC_METHOD(thread_add_ln1050_fu_233_p2);
    sensitive << ( indvar_flatten11_reg_130 );

    SC_METHOD(thread_add_ln1067_fu_203_p2);
    sensitive << ( indvar_flatten30_reg_119 );

    SC_METHOD(thread_and_ln1044_fu_171_p2);
    sensitive << ( icmp_ln1047_fu_165_p2 );
    sensitive << ( xor_ln1044_fu_159_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( fifo_C_drain_in_V_V_empty_n );
    sensitive << ( fifo_C_drain_out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln1067_reg_262 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( fifo_C_drain_in_V_V_empty_n );
    sensitive << ( fifo_C_drain_out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln1067_reg_262 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( fifo_C_drain_in_V_V_empty_n );
    sensitive << ( fifo_C_drain_out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln1067_reg_262 );

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_01001);
    sensitive << ( fifo_C_drain_out_V_V_full_n );
    sensitive << ( fifo_C_drain_local_in_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln1050_reg_281 );

    SC_METHOD(thread_ap_block_pp1_stage0_11001);
    sensitive << ( fifo_C_drain_out_V_V_full_n );
    sensitive << ( fifo_C_drain_local_in_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln1050_reg_281 );

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);
    sensitive << ( fifo_C_drain_out_V_V_full_n );
    sensitive << ( fifo_C_drain_local_in_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln1050_reg_281 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( fifo_C_drain_in_V_V_empty_n );
    sensitive << ( fifo_C_drain_out_V_V_full_n );
    sensitive << ( icmp_ln1067_reg_262 );

    SC_METHOD(thread_ap_block_state6_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state7_pp1_stage0_iter1);
    sensitive << ( fifo_C_drain_out_V_V_full_n );
    sensitive << ( fifo_C_drain_local_in_V_V_empty_n );
    sensitive << ( icmp_ln1050_reg_281 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( icmp_ln1067_fu_197_p2 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state6);
    sensitive << ( icmp_ln1050_fu_227_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( icmp_ln1043_fu_141_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_c3_V_fu_209_p2);
    sensitive << ( select_ln1047_reg_253 );

    SC_METHOD(thread_fifo_C_drain_in_V_V_blk_n);
    sensitive << ( fifo_C_drain_in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln1067_reg_262 );

    SC_METHOD(thread_fifo_C_drain_in_V_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln1067_reg_262 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_fifo_C_drain_local_in_V_V_blk_n);
    sensitive << ( fifo_C_drain_local_in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( icmp_ln1050_reg_281 );

    SC_METHOD(thread_fifo_C_drain_local_in_V_V_read);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln1050_reg_281 );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_fifo_C_drain_out_V_V_blk_n);
    sensitive << ( fifo_C_drain_out_V_V_full_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln1067_reg_262 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( icmp_ln1050_reg_281 );

    SC_METHOD(thread_fifo_C_drain_out_V_V_din);
    sensitive << ( fifo_C_drain_in_V_V_dout );
    sensitive << ( fifo_C_drain_local_in_V_V_dout );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln1067_reg_262 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln1050_reg_281 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( ap_block_pp1_stage0_01001 );

    SC_METHOD(thread_fifo_C_drain_out_V_V_write);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln1067_reg_262 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln1050_reg_281 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_icmp_ln1043_fu_141_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( indvar_flatten49_reg_85 );

    SC_METHOD(thread_icmp_ln1044_fu_153_p2);
    sensitive << ( icmp_ln1043_fu_141_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( indvar_flatten37_reg_96 );

    SC_METHOD(thread_icmp_ln1047_fu_165_p2);
    sensitive << ( icmp_ln1043_fu_141_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( p_026_0_reg_108 );

    SC_METHOD(thread_icmp_ln1050_fu_227_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( indvar_flatten11_reg_130 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_icmp_ln1067_fu_197_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten30_reg_119 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln879_fu_191_p2);
    sensitive << ( icmp_ln1043_fu_141_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( select_ln1047_fu_183_p3 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( icmp_ln1043_fu_141_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_or_ln1047_fu_177_p2);
    sensitive << ( icmp_ln1044_fu_153_p2 );
    sensitive << ( and_ln1044_fu_171_p2 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_select_ln1044_fu_220_p3);
    sensitive << ( icmp_ln1044_reg_248 );
    sensitive << ( add_ln1044_fu_214_p2 );

    SC_METHOD(thread_select_ln1047_fu_183_p3);
    sensitive << ( p_026_0_reg_108 );
    sensitive << ( or_ln1047_fu_177_p2 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_xor_ln1044_fu_159_p2);
    sensitive << ( icmp_ln1044_fu_153_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln1043_fu_141_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln879_fu_191_p2 );
    sensitive << ( icmp_ln1067_fu_197_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln1050_fu_227_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp1_stage0_subdone );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "C_drain_IO_L2_out_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, fifo_C_drain_in_V_V_dout, "(port)fifo_C_drain_in_V_V_dout");
    sc_trace(mVcdFile, fifo_C_drain_in_V_V_empty_n, "(port)fifo_C_drain_in_V_V_empty_n");
    sc_trace(mVcdFile, fifo_C_drain_in_V_V_read, "(port)fifo_C_drain_in_V_V_read");
    sc_trace(mVcdFile, fifo_C_drain_out_V_V_din, "(port)fifo_C_drain_out_V_V_din");
    sc_trace(mVcdFile, fifo_C_drain_out_V_V_full_n, "(port)fifo_C_drain_out_V_V_full_n");
    sc_trace(mVcdFile, fifo_C_drain_out_V_V_write, "(port)fifo_C_drain_out_V_V_write");
    sc_trace(mVcdFile, fifo_C_drain_local_in_V_V_dout, "(port)fifo_C_drain_local_in_V_V_dout");
    sc_trace(mVcdFile, fifo_C_drain_local_in_V_V_empty_n, "(port)fifo_C_drain_local_in_V_V_empty_n");
    sc_trace(mVcdFile, fifo_C_drain_local_in_V_V_read, "(port)fifo_C_drain_local_in_V_V_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, fifo_C_drain_in_V_V_blk_n, "fifo_C_drain_in_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln1067_reg_262, "icmp_ln1067_reg_262");
    sc_trace(mVcdFile, fifo_C_drain_out_V_V_blk_n, "fifo_C_drain_out_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, icmp_ln1050_reg_281, "icmp_ln1050_reg_281");
    sc_trace(mVcdFile, fifo_C_drain_local_in_V_V_blk_n, "fifo_C_drain_local_in_V_V_blk_n");
    sc_trace(mVcdFile, indvar_flatten30_reg_119, "indvar_flatten30_reg_119");
    sc_trace(mVcdFile, indvar_flatten11_reg_130, "indvar_flatten11_reg_130");
    sc_trace(mVcdFile, icmp_ln1043_fu_141_p2, "icmp_ln1043_fu_141_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, add_ln1043_fu_147_p2, "add_ln1043_fu_147_p2");
    sc_trace(mVcdFile, add_ln1043_reg_243, "add_ln1043_reg_243");
    sc_trace(mVcdFile, icmp_ln1044_fu_153_p2, "icmp_ln1044_fu_153_p2");
    sc_trace(mVcdFile, icmp_ln1044_reg_248, "icmp_ln1044_reg_248");
    sc_trace(mVcdFile, select_ln1047_fu_183_p3, "select_ln1047_fu_183_p3");
    sc_trace(mVcdFile, select_ln1047_reg_253, "select_ln1047_reg_253");
    sc_trace(mVcdFile, icmp_ln879_fu_191_p2, "icmp_ln879_fu_191_p2");
    sc_trace(mVcdFile, icmp_ln1067_fu_197_p2, "icmp_ln1067_fu_197_p2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, add_ln1067_fu_203_p2, "add_ln1067_fu_203_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, c3_V_fu_209_p2, "c3_V_fu_209_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, select_ln1044_fu_220_p3, "select_ln1044_fu_220_p3");
    sc_trace(mVcdFile, icmp_ln1050_fu_227_p2, "icmp_ln1050_fu_227_p2");
    sc_trace(mVcdFile, ap_block_state6_pp1_stage0_iter0, "ap_block_state6_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state7_pp1_stage0_iter1, "ap_block_state7_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, add_ln1050_fu_233_p2, "add_ln1050_fu_233_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state6, "ap_condition_pp1_exit_iter0_state6");
    sc_trace(mVcdFile, indvar_flatten49_reg_85, "indvar_flatten49_reg_85");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, indvar_flatten37_reg_96, "indvar_flatten37_reg_96");
    sc_trace(mVcdFile, p_026_0_reg_108, "p_026_0_reg_108");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, ap_block_pp1_stage0_01001, "ap_block_pp1_stage0_01001");
    sc_trace(mVcdFile, icmp_ln1047_fu_165_p2, "icmp_ln1047_fu_165_p2");
    sc_trace(mVcdFile, xor_ln1044_fu_159_p2, "xor_ln1044_fu_159_p2");
    sc_trace(mVcdFile, and_ln1044_fu_171_p2, "and_ln1044_fu_171_p2");
    sc_trace(mVcdFile, or_ln1047_fu_177_p2, "or_ln1047_fu_177_p2");
    sc_trace(mVcdFile, add_ln1044_fu_214_p2, "add_ln1044_fu_214_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
#endif

    }
}

C_drain_IO_L2_out::~C_drain_IO_L2_out() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void C_drain_IO_L2_out::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(icmp_ln1043_fu_141_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1043_fu_141_p2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln879_fu_191_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1043_fu_141_p2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln879_fu_191_p2.read()))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state6.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1043_fu_141_p2.read()) && 
                    esl_seteq<1,1,1>(icmp_ln879_fu_191_p2.read(), ap_const_lv1_1))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state6.read()))) {
            ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state6.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1043_fu_141_p2.read()) && 
                    esl_seteq<1,1,1>(icmp_ln879_fu_191_p2.read(), ap_const_lv1_1))) {
            ap_enable_reg_pp1_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1043_fu_141_p2.read()) && 
         esl_seteq<1,1,1>(icmp_ln879_fu_191_p2.read(), ap_const_lv1_1))) {
        indvar_flatten11_reg_130 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1050_fu_227_p2.read()))) {
        indvar_flatten11_reg_130 = add_ln1050_fu_233_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1043_fu_141_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln879_fu_191_p2.read()))) {
        indvar_flatten30_reg_119 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1067_fu_197_p2.read()))) {
        indvar_flatten30_reg_119 = add_ln1067_fu_203_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        indvar_flatten37_reg_96 = select_ln1044_fu_220_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        indvar_flatten37_reg_96 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        indvar_flatten49_reg_85 = add_ln1043_reg_243.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        indvar_flatten49_reg_85 = ap_const_lv6_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        p_026_0_reg_108 = c3_V_fu_209_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_026_0_reg_108 = ap_const_lv2_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        add_ln1043_reg_243 = add_ln1043_fu_147_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1043_fu_141_p2.read()))) {
        icmp_ln1044_reg_248 = icmp_ln1044_fu_153_p2.read();
        select_ln1047_reg_253 = select_ln1047_fu_183_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln1050_reg_281 = icmp_ln1050_fu_227_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln1067_reg_262 = icmp_ln1067_fu_197_p2.read();
    }
}

void C_drain_IO_L2_out::thread_add_ln1043_fu_147_p2() {
    add_ln1043_fu_147_p2 = (!indvar_flatten49_reg_85.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(indvar_flatten49_reg_85.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void C_drain_IO_L2_out::thread_add_ln1044_fu_214_p2() {
    add_ln1044_fu_214_p2 = (!indvar_flatten37_reg_96.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(indvar_flatten37_reg_96.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void C_drain_IO_L2_out::thread_add_ln1050_fu_233_p2() {
    add_ln1050_fu_233_p2 = (!indvar_flatten11_reg_130.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(indvar_flatten11_reg_130.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void C_drain_IO_L2_out::thread_add_ln1067_fu_203_p2() {
    add_ln1067_fu_203_p2 = (!indvar_flatten30_reg_119.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(indvar_flatten30_reg_119.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void C_drain_IO_L2_out::thread_and_ln1044_fu_171_p2() {
    and_ln1044_fu_171_p2 = (icmp_ln1047_fu_165_p2.read() & xor_ln1044_fu_159_p2.read());
}

void C_drain_IO_L2_out::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void C_drain_IO_L2_out::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[4];
}

void C_drain_IO_L2_out::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void C_drain_IO_L2_out::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void C_drain_IO_L2_out::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[3];
}

void C_drain_IO_L2_out::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void C_drain_IO_L2_out::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(icmp_ln1067_reg_262.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_in_V_V_empty_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln1067_reg_262.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_V_full_n.read()))));
}

void C_drain_IO_L2_out::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(icmp_ln1067_reg_262.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_in_V_V_empty_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln1067_reg_262.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_V_full_n.read()))));
}

void C_drain_IO_L2_out::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(icmp_ln1067_reg_262.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_in_V_V_empty_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln1067_reg_262.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_V_full_n.read()))));
}

void C_drain_IO_L2_out::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void C_drain_IO_L2_out::thread_ap_block_pp1_stage0_01001() {
    ap_block_pp1_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1050_reg_281.read()) && 
   esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_local_in_V_V_empty_n.read())) || 
  (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1050_reg_281.read()) && 
   esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_V_full_n.read()))));
}

void C_drain_IO_L2_out::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1050_reg_281.read()) && 
   esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_local_in_V_V_empty_n.read())) || 
  (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1050_reg_281.read()) && 
   esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_V_full_n.read()))));
}

void C_drain_IO_L2_out::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1050_reg_281.read()) && 
   esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_local_in_V_V_empty_n.read())) || 
  (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1050_reg_281.read()) && 
   esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_V_full_n.read()))));
}

void C_drain_IO_L2_out::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void C_drain_IO_L2_out::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void C_drain_IO_L2_out::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = ((esl_seteq<1,1,1>(icmp_ln1067_reg_262.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln1067_reg_262.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_V_full_n.read())));
}

void C_drain_IO_L2_out::thread_ap_block_state6_pp1_stage0_iter0() {
    ap_block_state6_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void C_drain_IO_L2_out::thread_ap_block_state7_pp1_stage0_iter1() {
    ap_block_state7_pp1_stage0_iter1 = ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1050_reg_281.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_local_in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1050_reg_281.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_V_full_n.read())));
}

void C_drain_IO_L2_out::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(icmp_ln1067_fu_197_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_ap_condition_pp1_exit_iter0_state6() {
    if (esl_seteq<1,1,1>(icmp_ln1050_fu_227_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp1_exit_iter0_state6 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state6 = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln1043_fu_141_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void C_drain_IO_L2_out::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void C_drain_IO_L2_out::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void C_drain_IO_L2_out::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void C_drain_IO_L2_out::thread_c3_V_fu_209_p2() {
    c3_V_fu_209_p2 = (!select_ln1047_reg_253.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(select_ln1047_reg_253.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void C_drain_IO_L2_out::thread_fifo_C_drain_in_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln1067_reg_262.read(), ap_const_lv1_0))) {
        fifo_C_drain_in_V_V_blk_n = fifo_C_drain_in_V_V_empty_n.read();
    } else {
        fifo_C_drain_in_V_V_blk_n = ap_const_logic_1;
    }
}

void C_drain_IO_L2_out::thread_fifo_C_drain_in_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln1067_reg_262.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        fifo_C_drain_in_V_V_read = ap_const_logic_1;
    } else {
        fifo_C_drain_in_V_V_read = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_fifo_C_drain_local_in_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1050_reg_281.read()))) {
        fifo_C_drain_local_in_V_V_blk_n = fifo_C_drain_local_in_V_V_empty_n.read();
    } else {
        fifo_C_drain_local_in_V_V_blk_n = ap_const_logic_1;
    }
}

void C_drain_IO_L2_out::thread_fifo_C_drain_local_in_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1050_reg_281.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        fifo_C_drain_local_in_V_V_read = ap_const_logic_1;
    } else {
        fifo_C_drain_local_in_V_V_read = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_fifo_C_drain_out_V_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(icmp_ln1067_reg_262.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1050_reg_281.read())))) {
        fifo_C_drain_out_V_V_blk_n = fifo_C_drain_out_V_V_full_n.read();
    } else {
        fifo_C_drain_out_V_V_blk_n = ap_const_logic_1;
    }
}

void C_drain_IO_L2_out::thread_fifo_C_drain_out_V_V_din() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1050_reg_281.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_01001.read(), ap_const_boolean_0))) {
        fifo_C_drain_out_V_V_din = fifo_C_drain_local_in_V_V_dout.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(icmp_ln1067_reg_262.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_01001.read(), ap_const_boolean_0))) {
        fifo_C_drain_out_V_V_din = fifo_C_drain_in_V_V_dout.read();
    } else {
        fifo_C_drain_out_V_V_din = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void C_drain_IO_L2_out::thread_fifo_C_drain_out_V_V_write() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(icmp_ln1067_reg_262.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1050_reg_281.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)))) {
        fifo_C_drain_out_V_V_write = ap_const_logic_1;
    } else {
        fifo_C_drain_out_V_V_write = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_icmp_ln1043_fu_141_p2() {
    icmp_ln1043_fu_141_p2 = (!indvar_flatten49_reg_85.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten49_reg_85.read() == ap_const_lv6_20);
}

void C_drain_IO_L2_out::thread_icmp_ln1044_fu_153_p2() {
    icmp_ln1044_fu_153_p2 = (!indvar_flatten37_reg_96.read().is_01() || !ap_const_lv5_8.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten37_reg_96.read() == ap_const_lv5_8);
}

void C_drain_IO_L2_out::thread_icmp_ln1047_fu_165_p2() {
    icmp_ln1047_fu_165_p2 = (!p_026_0_reg_108.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(p_026_0_reg_108.read() == ap_const_lv2_2);
}

void C_drain_IO_L2_out::thread_icmp_ln1050_fu_227_p2() {
    icmp_ln1050_fu_227_p2 = (!indvar_flatten11_reg_130.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten11_reg_130.read() == ap_const_lv6_20);
}

void C_drain_IO_L2_out::thread_icmp_ln1067_fu_197_p2() {
    icmp_ln1067_fu_197_p2 = (!indvar_flatten30_reg_119.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten30_reg_119.read() == ap_const_lv6_20);
}

void C_drain_IO_L2_out::thread_icmp_ln879_fu_191_p2() {
    icmp_ln879_fu_191_p2 = (!select_ln1047_fu_183_p3.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(select_ln1047_fu_183_p3.read() == ap_const_lv2_0);
}

void C_drain_IO_L2_out::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln1043_fu_141_p2.read(), ap_const_lv1_1))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_or_ln1047_fu_177_p2() {
    or_ln1047_fu_177_p2 = (and_ln1044_fu_171_p2.read() | icmp_ln1044_fu_153_p2.read());
}

void C_drain_IO_L2_out::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void C_drain_IO_L2_out::thread_select_ln1044_fu_220_p3() {
    select_ln1044_fu_220_p3 = (!icmp_ln1044_reg_248.read()[0].is_01())? sc_lv<5>(): ((icmp_ln1044_reg_248.read()[0].to_bool())? ap_const_lv5_1: add_ln1044_fu_214_p2.read());
}

void C_drain_IO_L2_out::thread_select_ln1047_fu_183_p3() {
    select_ln1047_fu_183_p3 = (!or_ln1047_fu_177_p2.read()[0].is_01())? sc_lv<2>(): ((or_ln1047_fu_177_p2.read()[0].to_bool())? ap_const_lv2_0: p_026_0_reg_108.read());
}

void C_drain_IO_L2_out::thread_start_out() {
    start_out = real_start.read();
}

void C_drain_IO_L2_out::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_xor_ln1044_fu_159_p2() {
    xor_ln1044_fu_159_p2 = (icmp_ln1044_fu_153_p2.read() ^ ap_const_lv1_1);
}

void C_drain_IO_L2_out::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln1043_fu_141_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln1043_fu_141_p2.read()) && esl_seteq<1,1,1>(icmp_ln879_fu_191_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln1067_fu_197_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln1067_fu_197_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 16 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln1050_fu_227_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln1050_fu_227_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}

}

