// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _C_drain_IO_L3_out_serialize_HH_
#define _C_drain_IO_L3_out_serialize_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct C_drain_IO_L3_out_serialize : public sc_module {
    // Port declarations 58
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > m_axi_C_V_AWVALID;
    sc_in< sc_logic > m_axi_C_V_AWREADY;
    sc_out< sc_lv<32> > m_axi_C_V_AWADDR;
    sc_out< sc_lv<1> > m_axi_C_V_AWID;
    sc_out< sc_lv<32> > m_axi_C_V_AWLEN;
    sc_out< sc_lv<3> > m_axi_C_V_AWSIZE;
    sc_out< sc_lv<2> > m_axi_C_V_AWBURST;
    sc_out< sc_lv<2> > m_axi_C_V_AWLOCK;
    sc_out< sc_lv<4> > m_axi_C_V_AWCACHE;
    sc_out< sc_lv<3> > m_axi_C_V_AWPROT;
    sc_out< sc_lv<4> > m_axi_C_V_AWQOS;
    sc_out< sc_lv<4> > m_axi_C_V_AWREGION;
    sc_out< sc_lv<1> > m_axi_C_V_AWUSER;
    sc_out< sc_logic > m_axi_C_V_WVALID;
    sc_in< sc_logic > m_axi_C_V_WREADY;
    sc_out< sc_lv<512> > m_axi_C_V_WDATA;
    sc_out< sc_lv<64> > m_axi_C_V_WSTRB;
    sc_out< sc_logic > m_axi_C_V_WLAST;
    sc_out< sc_lv<1> > m_axi_C_V_WID;
    sc_out< sc_lv<1> > m_axi_C_V_WUSER;
    sc_out< sc_logic > m_axi_C_V_ARVALID;
    sc_in< sc_logic > m_axi_C_V_ARREADY;
    sc_out< sc_lv<32> > m_axi_C_V_ARADDR;
    sc_out< sc_lv<1> > m_axi_C_V_ARID;
    sc_out< sc_lv<32> > m_axi_C_V_ARLEN;
    sc_out< sc_lv<3> > m_axi_C_V_ARSIZE;
    sc_out< sc_lv<2> > m_axi_C_V_ARBURST;
    sc_out< sc_lv<2> > m_axi_C_V_ARLOCK;
    sc_out< sc_lv<4> > m_axi_C_V_ARCACHE;
    sc_out< sc_lv<3> > m_axi_C_V_ARPROT;
    sc_out< sc_lv<4> > m_axi_C_V_ARQOS;
    sc_out< sc_lv<4> > m_axi_C_V_ARREGION;
    sc_out< sc_lv<1> > m_axi_C_V_ARUSER;
    sc_in< sc_logic > m_axi_C_V_RVALID;
    sc_out< sc_logic > m_axi_C_V_RREADY;
    sc_in< sc_lv<512> > m_axi_C_V_RDATA;
    sc_in< sc_logic > m_axi_C_V_RLAST;
    sc_in< sc_lv<1> > m_axi_C_V_RID;
    sc_in< sc_lv<1> > m_axi_C_V_RUSER;
    sc_in< sc_lv<2> > m_axi_C_V_RRESP;
    sc_in< sc_logic > m_axi_C_V_BVALID;
    sc_out< sc_logic > m_axi_C_V_BREADY;
    sc_in< sc_lv<2> > m_axi_C_V_BRESP;
    sc_in< sc_lv<1> > m_axi_C_V_BID;
    sc_in< sc_lv<1> > m_axi_C_V_BUSER;
    sc_in< sc_lv<32> > C_V_offset_dout;
    sc_in< sc_logic > C_V_offset_empty_n;
    sc_out< sc_logic > C_V_offset_read;
    sc_in< sc_lv<128> > fifo_C_drain_local_in_V_V_dout;
    sc_in< sc_logic > fifo_C_drain_local_in_V_V_empty_n;
    sc_out< sc_logic > fifo_C_drain_local_in_V_V_read;


    // Module declarations
    C_drain_IO_L3_out_serialize(sc_module_name name);
    SC_HAS_PROCESS(C_drain_IO_L3_out_serialize);

    ~C_drain_IO_L3_out_serialize();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<11> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > C_V_blk_n_AW;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > C_V_blk_n_W;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_pp0_stage1;
    sc_signal< sc_lv<1> > icmp_ln1164_reg_159;
    sc_signal< sc_lv<1> > icmp_ln1164_reg_159_pp0_iter1_reg;
    sc_signal< sc_logic > C_V_blk_n_B;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_logic > C_V_offset_blk_n;
    sc_signal< sc_logic > fifo_C_drain_local_in_V_V_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage2;
    sc_signal< bool > ap_block_pp0_stage2;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage3;
    sc_signal< bool > ap_block_pp0_stage3;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<9> > t_V_reg_96;
    sc_signal< sc_lv<26> > C_V_offset1_i_reg_148;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<1> > icmp_ln1164_fu_127_p2;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state7_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<9> > i_V_fu_133_p2;
    sc_signal< sc_lv<9> > i_V_reg_163;
    sc_signal< sc_lv<128> > tmp_V_reg_168;
    sc_signal< bool > ap_block_state4_pp0_stage1_iter0;
    sc_signal< bool > ap_block_state8_pp0_stage1_iter1;
    sc_signal< bool > ap_block_state8_io;
    sc_signal< bool > ap_block_pp0_stage1_11001;
    sc_signal< sc_lv<128> > tmp_V_2_reg_173;
    sc_signal< bool > ap_block_state5_pp0_stage2_iter0;
    sc_signal< bool > ap_block_pp0_stage2_11001;
    sc_signal< sc_lv<128> > tmp_V_3_reg_178;
    sc_signal< bool > ap_block_state6_pp0_stage3_iter0;
    sc_signal< bool > ap_block_pp0_stage3_11001;
    sc_signal< sc_lv<128> > tmp_V_4_reg_183;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state3;
    sc_signal< bool > ap_block_pp0_stage3_subdone;
    sc_signal< bool > ap_block_pp0_stage1_subdone;
    sc_signal< sc_lv<9> > ap_phi_mux_t_V_phi_fu_100_p4;
    sc_signal< sc_lv<64> > zext_ln1159_fu_117_p1;
    sc_signal< bool > ap_block_pp0_stage1_01001;
    sc_signal< sc_lv<11> > ap_NS_fsm;
    sc_signal< bool > ap_block_pp0_stage2_subdone;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<11> ap_ST_fsm_state1;
    static const sc_lv<11> ap_ST_fsm_state2;
    static const sc_lv<11> ap_ST_fsm_pp0_stage0;
    static const sc_lv<11> ap_ST_fsm_pp0_stage1;
    static const sc_lv<11> ap_ST_fsm_pp0_stage2;
    static const sc_lv<11> ap_ST_fsm_pp0_stage3;
    static const sc_lv<11> ap_ST_fsm_state9;
    static const sc_lv<11> ap_ST_fsm_state10;
    static const sc_lv<11> ap_ST_fsm_state11;
    static const sc_lv<11> ap_ST_fsm_state12;
    static const sc_lv<11> ap_ST_fsm_state13;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<32> ap_const_lv32_100;
    static const sc_lv<64> ap_const_lv64_FFFFFFFFFFFFFFFF;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<9> ap_const_lv9_100;
    static const sc_lv<9> ap_const_lv9_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_C_V_blk_n_AW();
    void thread_C_V_blk_n_B();
    void thread_C_V_blk_n_W();
    void thread_C_V_offset_blk_n();
    void thread_C_V_offset_read();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_pp0_stage1();
    void thread_ap_CS_fsm_pp0_stage2();
    void thread_ap_CS_fsm_pp0_stage3();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state2();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_pp0_stage1();
    void thread_ap_block_pp0_stage1_01001();
    void thread_ap_block_pp0_stage1_11001();
    void thread_ap_block_pp0_stage1_subdone();
    void thread_ap_block_pp0_stage2();
    void thread_ap_block_pp0_stage2_11001();
    void thread_ap_block_pp0_stage2_subdone();
    void thread_ap_block_pp0_stage3();
    void thread_ap_block_pp0_stage3_11001();
    void thread_ap_block_pp0_stage3_subdone();
    void thread_ap_block_state1();
    void thread_ap_block_state3_pp0_stage0_iter0();
    void thread_ap_block_state4_pp0_stage1_iter0();
    void thread_ap_block_state5_pp0_stage2_iter0();
    void thread_ap_block_state6_pp0_stage3_iter0();
    void thread_ap_block_state7_pp0_stage0_iter1();
    void thread_ap_block_state8_io();
    void thread_ap_block_state8_pp0_stage1_iter1();
    void thread_ap_condition_pp0_exit_iter0_state3();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_phi_mux_t_V_phi_fu_100_p4();
    void thread_ap_ready();
    void thread_fifo_C_drain_local_in_V_V_blk_n();
    void thread_fifo_C_drain_local_in_V_V_read();
    void thread_i_V_fu_133_p2();
    void thread_icmp_ln1164_fu_127_p2();
    void thread_m_axi_C_V_ARADDR();
    void thread_m_axi_C_V_ARBURST();
    void thread_m_axi_C_V_ARCACHE();
    void thread_m_axi_C_V_ARID();
    void thread_m_axi_C_V_ARLEN();
    void thread_m_axi_C_V_ARLOCK();
    void thread_m_axi_C_V_ARPROT();
    void thread_m_axi_C_V_ARQOS();
    void thread_m_axi_C_V_ARREGION();
    void thread_m_axi_C_V_ARSIZE();
    void thread_m_axi_C_V_ARUSER();
    void thread_m_axi_C_V_ARVALID();
    void thread_m_axi_C_V_AWADDR();
    void thread_m_axi_C_V_AWBURST();
    void thread_m_axi_C_V_AWCACHE();
    void thread_m_axi_C_V_AWID();
    void thread_m_axi_C_V_AWLEN();
    void thread_m_axi_C_V_AWLOCK();
    void thread_m_axi_C_V_AWPROT();
    void thread_m_axi_C_V_AWQOS();
    void thread_m_axi_C_V_AWREGION();
    void thread_m_axi_C_V_AWSIZE();
    void thread_m_axi_C_V_AWUSER();
    void thread_m_axi_C_V_AWVALID();
    void thread_m_axi_C_V_BREADY();
    void thread_m_axi_C_V_RREADY();
    void thread_m_axi_C_V_WDATA();
    void thread_m_axi_C_V_WID();
    void thread_m_axi_C_V_WLAST();
    void thread_m_axi_C_V_WSTRB();
    void thread_m_axi_C_V_WUSER();
    void thread_m_axi_C_V_WVALID();
    void thread_zext_ln1159_fu_117_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
