// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module kernel0_C_drain_IO_L2_out (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        fifo_C_drain_C_drain_IO_L2_out_1_dout,
        fifo_C_drain_C_drain_IO_L2_out_1_num_data_valid,
        fifo_C_drain_C_drain_IO_L2_out_1_fifo_cap,
        fifo_C_drain_C_drain_IO_L2_out_1_empty_n,
        fifo_C_drain_C_drain_IO_L2_out_1_read,
        fifo_C_drain_C_drain_IO_L2_out_0_din,
        fifo_C_drain_C_drain_IO_L2_out_0_num_data_valid,
        fifo_C_drain_C_drain_IO_L2_out_0_fifo_cap,
        fifo_C_drain_C_drain_IO_L2_out_0_full_n,
        fifo_C_drain_C_drain_IO_L2_out_0_write,
        fifo_C_drain_C_drain_IO_L1_out_0_0_dout,
        fifo_C_drain_C_drain_IO_L1_out_0_0_num_data_valid,
        fifo_C_drain_C_drain_IO_L1_out_0_0_fifo_cap,
        fifo_C_drain_C_drain_IO_L1_out_0_0_empty_n,
        fifo_C_drain_C_drain_IO_L1_out_0_0_read
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [127:0] fifo_C_drain_C_drain_IO_L2_out_1_dout;
input  [1:0] fifo_C_drain_C_drain_IO_L2_out_1_num_data_valid;
input  [1:0] fifo_C_drain_C_drain_IO_L2_out_1_fifo_cap;
input   fifo_C_drain_C_drain_IO_L2_out_1_empty_n;
output   fifo_C_drain_C_drain_IO_L2_out_1_read;
output  [127:0] fifo_C_drain_C_drain_IO_L2_out_0_din;
input  [1:0] fifo_C_drain_C_drain_IO_L2_out_0_num_data_valid;
input  [1:0] fifo_C_drain_C_drain_IO_L2_out_0_fifo_cap;
input   fifo_C_drain_C_drain_IO_L2_out_0_full_n;
output   fifo_C_drain_C_drain_IO_L2_out_0_write;
input  [127:0] fifo_C_drain_C_drain_IO_L1_out_0_0_dout;
input  [1:0] fifo_C_drain_C_drain_IO_L1_out_0_0_num_data_valid;
input  [1:0] fifo_C_drain_C_drain_IO_L1_out_0_0_fifo_cap;
input   fifo_C_drain_C_drain_IO_L1_out_0_0_empty_n;
output   fifo_C_drain_C_drain_IO_L1_out_0_0_read;

reg ap_done;
reg ap_idle;
reg start_write;
reg fifo_C_drain_C_drain_IO_L2_out_1_read;
reg[127:0] fifo_C_drain_C_drain_IO_L2_out_0_din;
reg fifo_C_drain_C_drain_IO_L2_out_0_write;
reg fifo_C_drain_C_drain_IO_L1_out_0_0_read;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [5:0] add_ln1043_fu_119_p2;
reg   [5:0] add_ln1043_reg_228;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln1044_fu_128_p2;
reg   [0:0] icmp_ln1044_reg_233;
wire   [0:0] icmp_ln1043_fu_113_p2;
wire   [1:0] select_ln1044_fu_158_p3;
reg   [1:0] select_ln1044_reg_238;
wire   [0:0] icmp_ln1049_fu_166_p2;
reg   [0:0] icmp_ln1049_reg_243;
wire    grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_start;
wire    grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_done;
wire    grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_idle;
wire    grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_ready;
wire    grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_fifo_C_drain_C_drain_IO_L2_out_1_read;
wire   [127:0] grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_fifo_C_drain_C_drain_IO_L2_out_0_din;
wire    grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_fifo_C_drain_C_drain_IO_L2_out_0_write;
wire    grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_start;
wire    grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_done;
wire    grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_idle;
wire    grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_ready;
wire    grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_fifo_C_drain_C_drain_IO_L1_out_0_0_read;
wire   [127:0] grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_fifo_C_drain_C_drain_IO_L2_out_0_din;
wire    grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_fifo_C_drain_C_drain_IO_L2_out_0_write;
reg    grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_start_reg;
reg   [1:0] c3_fu_64;
wire   [1:0] c3_1_fu_172_p2;
reg    ap_block_state3_on_subcall_done;
reg    ap_block_state1;
reg   [4:0] indvar_flatten35_fu_68;
wire   [4:0] select_ln1044_1_fu_183_p3;
reg   [5:0] indvar_flatten46_fu_72;
wire   [0:0] icmp_ln1047_fu_140_p2;
wire   [0:0] xor_ln1043_fu_134_p2;
wire   [0:0] and_ln1043_fu_146_p2;
wire   [0:0] or_ln1044_fu_152_p2;
wire   [4:0] add_ln1044_fu_177_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_start_reg = 1'b0;
#0 grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_start_reg = 1'b0;
end

kernel0_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_start),
    .ap_done(grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_done),
    .ap_idle(grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_idle),
    .ap_ready(grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_ready),
    .fifo_C_drain_C_drain_IO_L2_out_1_dout(fifo_C_drain_C_drain_IO_L2_out_1_dout),
    .fifo_C_drain_C_drain_IO_L2_out_1_num_data_valid(2'd0),
    .fifo_C_drain_C_drain_IO_L2_out_1_fifo_cap(2'd0),
    .fifo_C_drain_C_drain_IO_L2_out_1_empty_n(fifo_C_drain_C_drain_IO_L2_out_1_empty_n),
    .fifo_C_drain_C_drain_IO_L2_out_1_read(grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_fifo_C_drain_C_drain_IO_L2_out_1_read),
    .fifo_C_drain_C_drain_IO_L2_out_0_din(grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_fifo_C_drain_C_drain_IO_L2_out_0_din),
    .fifo_C_drain_C_drain_IO_L2_out_0_num_data_valid(2'd0),
    .fifo_C_drain_C_drain_IO_L2_out_0_fifo_cap(2'd0),
    .fifo_C_drain_C_drain_IO_L2_out_0_full_n(fifo_C_drain_C_drain_IO_L2_out_0_full_n),
    .fifo_C_drain_C_drain_IO_L2_out_0_write(grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_fifo_C_drain_C_drain_IO_L2_out_0_write)
);

kernel0_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_start),
    .ap_done(grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_done),
    .ap_idle(grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_idle),
    .ap_ready(grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_ready),
    .fifo_C_drain_C_drain_IO_L1_out_0_0_dout(fifo_C_drain_C_drain_IO_L1_out_0_0_dout),
    .fifo_C_drain_C_drain_IO_L1_out_0_0_num_data_valid(2'd0),
    .fifo_C_drain_C_drain_IO_L1_out_0_0_fifo_cap(2'd0),
    .fifo_C_drain_C_drain_IO_L1_out_0_0_empty_n(fifo_C_drain_C_drain_IO_L1_out_0_0_empty_n),
    .fifo_C_drain_C_drain_IO_L1_out_0_0_read(grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_fifo_C_drain_C_drain_IO_L1_out_0_0_read),
    .fifo_C_drain_C_drain_IO_L2_out_0_din(grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_fifo_C_drain_C_drain_IO_L2_out_0_din),
    .fifo_C_drain_C_drain_IO_L2_out_0_num_data_valid(2'd0),
    .fifo_C_drain_C_drain_IO_L2_out_0_fifo_cap(2'd0),
    .fifo_C_drain_C_drain_IO_L2_out_0_full_n(fifo_C_drain_C_drain_IO_L2_out_0_full_n),
    .fifo_C_drain_C_drain_IO_L2_out_0_write(grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_fifo_C_drain_C_drain_IO_L2_out_0_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln1043_fu_113_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1049_fu_166_p2 == 1'd1) & (icmp_ln1043_fu_113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_start_reg <= 1'b1;
        end else if ((grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_ready == 1'b1)) begin
            grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1049_fu_166_p2 == 1'd0) & (icmp_ln1043_fu_113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_start_reg <= 1'b1;
        end else if ((grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_ready == 1'b1)) begin
            grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        c3_fu_64 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_on_subcall_done))) begin
        c3_fu_64 <= c3_1_fu_172_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten35_fu_68 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_on_subcall_done))) begin
        indvar_flatten35_fu_68 <= select_ln1044_1_fu_183_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten46_fu_72 <= 6'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_on_subcall_done))) begin
        indvar_flatten46_fu_72 <= add_ln1043_reg_228;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln1043_reg_228 <= add_ln1043_fu_119_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1043_fu_113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_ln1044_reg_233 <= icmp_ln1044_fu_128_p2;
        icmp_ln1049_reg_243 <= icmp_ln1049_fu_166_p2;
        select_ln1044_reg_238 <= select_ln1044_fu_158_p3;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1043_fu_113_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1049_reg_243 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        fifo_C_drain_C_drain_IO_L1_out_0_0_read = grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_fifo_C_drain_C_drain_IO_L1_out_0_0_read;
    end else begin
        fifo_C_drain_C_drain_IO_L1_out_0_0_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1049_reg_243 == 1'd1)) begin
            fifo_C_drain_C_drain_IO_L2_out_0_din = grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_fifo_C_drain_C_drain_IO_L2_out_0_din;
        end else if ((icmp_ln1049_reg_243 == 1'd0)) begin
            fifo_C_drain_C_drain_IO_L2_out_0_din = grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_fifo_C_drain_C_drain_IO_L2_out_0_din;
        end else begin
            fifo_C_drain_C_drain_IO_L2_out_0_din = grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_fifo_C_drain_C_drain_IO_L2_out_0_din;
        end
    end else begin
        fifo_C_drain_C_drain_IO_L2_out_0_din = grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_fifo_C_drain_C_drain_IO_L2_out_0_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1049_reg_243 == 1'd1)) begin
            fifo_C_drain_C_drain_IO_L2_out_0_write = grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_fifo_C_drain_C_drain_IO_L2_out_0_write;
        end else if ((icmp_ln1049_reg_243 == 1'd0)) begin
            fifo_C_drain_C_drain_IO_L2_out_0_write = grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_fifo_C_drain_C_drain_IO_L2_out_0_write;
        end else begin
            fifo_C_drain_C_drain_IO_L2_out_0_write = 1'b0;
        end
    end else begin
        fifo_C_drain_C_drain_IO_L2_out_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1049_reg_243 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        fifo_C_drain_C_drain_IO_L2_out_1_read = grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_fifo_C_drain_C_drain_IO_L2_out_1_read;
    end else begin
        fifo_C_drain_C_drain_IO_L2_out_1_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1043_fu_113_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln1043_fu_113_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1043_fu_119_p2 = (indvar_flatten46_fu_72 + 6'd1);

assign add_ln1044_fu_177_p2 = (indvar_flatten35_fu_68 + 5'd1);

assign and_ln1043_fu_146_p2 = (xor_ln1043_fu_134_p2 & icmp_ln1047_fu_140_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = (((grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_done == 1'b0) & (icmp_ln1049_reg_243 == 1'd1)) | ((grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_done == 1'b0) & (icmp_ln1049_reg_243 == 1'd0)));
end

assign ap_ready = internal_ap_ready;

assign c3_1_fu_172_p2 = (select_ln1044_reg_238 + 2'd1);

assign grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_start = grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1050_4_VITIS_fu_84_ap_start_reg;

assign grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_start = grp_C_drain_IO_L2_out_Pipeline_VITIS_LOOP_1067_7_VITIS_fu_76_ap_start_reg;

assign icmp_ln1043_fu_113_p2 = ((indvar_flatten46_fu_72 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln1044_fu_128_p2 = ((indvar_flatten35_fu_68 == 5'd8) ? 1'b1 : 1'b0);

assign icmp_ln1047_fu_140_p2 = ((c3_fu_64 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln1049_fu_166_p2 = ((select_ln1044_fu_158_p3 == 2'd0) ? 1'b1 : 1'b0);

assign or_ln1044_fu_152_p2 = (icmp_ln1044_fu_128_p2 | and_ln1043_fu_146_p2);

assign select_ln1044_1_fu_183_p3 = ((icmp_ln1044_reg_233[0:0] == 1'b1) ? 5'd1 : add_ln1044_fu_177_p2);

assign select_ln1044_fu_158_p3 = ((or_ln1044_fu_152_p2[0:0] == 1'b1) ? 2'd0 : c3_fu_64);

assign start_out = real_start;

assign xor_ln1043_fu_134_p2 = (icmp_ln1044_fu_128_p2 ^ 1'd1);

endmodule //kernel0_C_drain_IO_L2_out
