// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module A_IO_L2_in_boundary (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        fifo_A_in_V_V_dout,
        fifo_A_in_V_V_empty_n,
        fifo_A_in_V_V_read,
        fifo_A_local_out_V_V_din,
        fifo_A_local_out_V_V_full_n,
        fifo_A_local_out_V_V_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [511:0] fifo_A_in_V_V_dout;
input   fifo_A_in_V_V_empty_n;
output   fifo_A_in_V_V_read;
output  [63:0] fifo_A_local_out_V_V_din;
input   fifo_A_local_out_V_V_full_n;
output   fifo_A_local_out_V_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg fifo_A_in_V_V_read;
reg fifo_A_local_out_V_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [2:0] c0_V_fu_133_p2;
reg   [2:0] c0_V_reg_184;
wire    ap_CS_fsm_state2;
reg   [0:0] intra_trans_en_0_load_reg_189;
wire   [0:0] icmp_ln270_fu_127_p2;
wire   [2:0] c1_V_fu_145_p2;
reg   [2:0] c1_V_reg_197;
wire    ap_CS_fsm_state3;
wire   [2:0] c2_V_fu_157_p2;
reg   [2:0] c2_V_reg_205;
wire    ap_CS_fsm_state4;
reg   [0:0] intra_trans_en_0_load_3_reg_210;
wire   [0:0] icmp_ln272_fu_151_p2;
wire   [0:0] xor_ln316_fu_163_p2;
wire    ap_CS_fsm_state5;
wire    grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_ready;
wire    grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_done;
reg   [0:0] arb_2_reg_91;
wire    grp_A_IO_L2_in_intra_trans_fu_103_ap_ready;
wire    grp_A_IO_L2_in_intra_trans_fu_103_ap_done;
reg    ap_block_state5_on_subcall_done;
reg    local_A_ping_V_ce0;
wire   [511:0] local_A_ping_V_q0;
reg    local_A_ping_V_ce1;
reg    local_A_ping_V_we1;
reg    local_A_pong_V_ce0;
wire   [511:0] local_A_pong_V_q0;
reg    local_A_pong_V_ce1;
reg    local_A_pong_V_we1;
wire    grp_A_IO_L2_in_intra_trans_fu_103_ap_start;
wire    grp_A_IO_L2_in_intra_trans_fu_103_ap_idle;
wire   [2:0] grp_A_IO_L2_in_intra_trans_fu_103_local_A_V_address0;
wire    grp_A_IO_L2_in_intra_trans_fu_103_local_A_V_ce0;
reg   [511:0] grp_A_IO_L2_in_intra_trans_fu_103_local_A_V_q0;
wire   [63:0] grp_A_IO_L2_in_intra_trans_fu_103_fifo_A_local_out_V_V_din;
wire    grp_A_IO_L2_in_intra_trans_fu_103_fifo_A_local_out_V_V_write;
reg    grp_A_IO_L2_in_intra_trans_fu_103_intra_trans_en;
wire    grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_start;
wire    grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_idle;
wire   [2:0] grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_address1;
wire    grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_ce1;
wire    grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_we1;
wire   [511:0] grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_d1;
wire    grp_A_IO_L2_in_inter_trans_boundary_fu_111_fifo_A_in_V_V_read;
reg   [2:0] p_016_0_reg_58;
reg    ap_block_state1;
wire   [0:0] icmp_ln271_fu_139_p2;
reg   [2:0] p_047_0_reg_69;
reg   [2:0] p_060_0_reg_80;
wire   [0:0] ap_phi_mux_arb_2_phi_fu_95_p4;
reg    grp_A_IO_L2_in_intra_trans_fu_103_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_start_reg;
reg   [0:0] intra_trans_en_0_fu_46;
reg   [5:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 grp_A_IO_L2_in_intra_trans_fu_103_ap_start_reg = 1'b0;
#0 grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_start_reg = 1'b0;
end

A_IO_L2_in_local_A_ping_V #(
    .DataWidth( 512 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
local_A_ping_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_A_IO_L2_in_intra_trans_fu_103_local_A_V_address0),
    .ce0(local_A_ping_V_ce0),
    .q0(local_A_ping_V_q0),
    .address1(grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_address1),
    .ce1(local_A_ping_V_ce1),
    .we1(local_A_ping_V_we1),
    .d1(grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_d1)
);

A_IO_L2_in_local_A_ping_V #(
    .DataWidth( 512 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
local_A_pong_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_A_IO_L2_in_intra_trans_fu_103_local_A_V_address0),
    .ce0(local_A_pong_V_ce0),
    .q0(local_A_pong_V_q0),
    .address1(grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_address1),
    .ce1(local_A_pong_V_ce1),
    .we1(local_A_pong_V_we1),
    .d1(grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_d1)
);

A_IO_L2_in_intra_trans grp_A_IO_L2_in_intra_trans_fu_103(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_A_IO_L2_in_intra_trans_fu_103_ap_start),
    .ap_done(grp_A_IO_L2_in_intra_trans_fu_103_ap_done),
    .ap_idle(grp_A_IO_L2_in_intra_trans_fu_103_ap_idle),
    .ap_ready(grp_A_IO_L2_in_intra_trans_fu_103_ap_ready),
    .local_A_V_address0(grp_A_IO_L2_in_intra_trans_fu_103_local_A_V_address0),
    .local_A_V_ce0(grp_A_IO_L2_in_intra_trans_fu_103_local_A_V_ce0),
    .local_A_V_q0(grp_A_IO_L2_in_intra_trans_fu_103_local_A_V_q0),
    .fifo_A_local_out_V_V_din(grp_A_IO_L2_in_intra_trans_fu_103_fifo_A_local_out_V_V_din),
    .fifo_A_local_out_V_V_full_n(fifo_A_local_out_V_V_full_n),
    .fifo_A_local_out_V_V_write(grp_A_IO_L2_in_intra_trans_fu_103_fifo_A_local_out_V_V_write),
    .intra_trans_en(grp_A_IO_L2_in_intra_trans_fu_103_intra_trans_en)
);

A_IO_L2_in_inter_trans_boundary grp_A_IO_L2_in_inter_trans_boundary_fu_111(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_start),
    .ap_done(grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_done),
    .ap_idle(grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_idle),
    .ap_ready(grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_ready),
    .local_A_V_address1(grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_address1),
    .local_A_V_ce1(grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_ce1),
    .local_A_V_we1(grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_we1),
    .local_A_V_d1(grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_d1),
    .fifo_A_in_V_V_dout(fifo_A_in_V_V_dout),
    .fifo_A_in_V_V_empty_n(fifo_A_in_V_V_empty_n),
    .fifo_A_in_V_V_read(grp_A_IO_L2_in_inter_trans_boundary_fu_111_fifo_A_in_V_V_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_A_IO_L2_in_intra_trans_fu_103_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_start_reg <= 1'b0;
    end else begin
        if ((((icmp_ln272_fu_151_p2 == 1'd0) & (ap_phi_mux_arb_2_phi_fu_95_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((ap_phi_mux_arb_2_phi_fu_95_p4 == 1'd0) & (icmp_ln272_fu_151_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
            grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_start_reg <= 1'b1;
        end else if ((grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_ready == 1'b1)) begin
            grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_A_IO_L2_in_intra_trans_fu_103_ap_start_reg <= 1'b0;
    end else begin
        if ((((icmp_ln272_fu_151_p2 == 1'd0) & (ap_phi_mux_arb_2_phi_fu_95_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((ap_phi_mux_arb_2_phi_fu_95_p4 == 1'd0) & (icmp_ln272_fu_151_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln270_fu_127_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
            grp_A_IO_L2_in_intra_trans_fu_103_ap_start_reg <= 1'b1;
        end else if ((grp_A_IO_L2_in_intra_trans_fu_103_ap_ready == 1'b1)) begin
            grp_A_IO_L2_in_intra_trans_fu_103_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_139_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        arb_2_reg_91 <= 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5_on_subcall_done))) begin
        arb_2_reg_91 <= xor_ln316_fu_163_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5_on_subcall_done))) begin
        intra_trans_en_0_fu_46 <= 1'd1;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        intra_trans_en_0_fu_46 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_139_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_016_0_reg_58 <= c0_V_reg_184;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_016_0_reg_58 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln270_fu_127_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        p_047_0_reg_69 <= 3'd0;
    end else if (((icmp_ln272_fu_151_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_047_0_reg_69 <= c1_V_reg_197;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_139_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        p_060_0_reg_80 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5_on_subcall_done))) begin
        p_060_0_reg_80 <= c2_V_reg_205;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        c0_V_reg_184 <= c0_V_fu_133_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        c1_V_reg_197 <= c1_V_fu_145_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c2_V_reg_205 <= c2_V_fu_157_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln272_fu_151_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        intra_trans_en_0_load_3_reg_210 <= intra_trans_en_0_fu_46;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln270_fu_127_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        intra_trans_en_0_load_reg_189 <= intra_trans_en_0_fu_46;
    end
end

always @ (*) begin
    if (((grp_A_IO_L2_in_intra_trans_fu_103_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((arb_2_reg_91 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((arb_2_reg_91 == 1'd1) & (1'b1 == ap_CS_fsm_state5)))) begin
        fifo_A_in_V_V_read = grp_A_IO_L2_in_inter_trans_boundary_fu_111_fifo_A_in_V_V_read;
    end else begin
        fifo_A_in_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((arb_2_reg_91 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((arb_2_reg_91 == 1'd1) & (1'b1 == ap_CS_fsm_state5)))) begin
        fifo_A_local_out_V_V_write = grp_A_IO_L2_in_intra_trans_fu_103_fifo_A_local_out_V_V_write;
    end else begin
        fifo_A_local_out_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((arb_2_reg_91 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((arb_2_reg_91 == 1'd1) & (1'b1 == ap_CS_fsm_state5)))) begin
        grp_A_IO_L2_in_intra_trans_fu_103_intra_trans_en = intra_trans_en_0_load_3_reg_210;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_A_IO_L2_in_intra_trans_fu_103_intra_trans_en = intra_trans_en_0_load_reg_189;
    end else begin
        grp_A_IO_L2_in_intra_trans_fu_103_intra_trans_en = 'bx;
    end
end

always @ (*) begin
    if (((arb_2_reg_91 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        grp_A_IO_L2_in_intra_trans_fu_103_local_A_V_q0 = local_A_pong_V_q0;
    end else if (((1'b1 == ap_CS_fsm_state6) | ((arb_2_reg_91 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        grp_A_IO_L2_in_intra_trans_fu_103_local_A_V_q0 = local_A_ping_V_q0;
    end else begin
        grp_A_IO_L2_in_intra_trans_fu_103_local_A_V_q0 = 'bx;
    end
end

always @ (*) begin
    if (((grp_A_IO_L2_in_intra_trans_fu_103_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((arb_2_reg_91 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        local_A_ping_V_ce0 = grp_A_IO_L2_in_intra_trans_fu_103_local_A_V_ce0;
    end else begin
        local_A_ping_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((arb_2_reg_91 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        local_A_ping_V_ce1 = grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_ce1;
    end else begin
        local_A_ping_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((arb_2_reg_91 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        local_A_ping_V_we1 = grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_we1;
    end else begin
        local_A_ping_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((arb_2_reg_91 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        local_A_pong_V_ce0 = grp_A_IO_L2_in_intra_trans_fu_103_local_A_V_ce0;
    end else begin
        local_A_pong_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((arb_2_reg_91 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        local_A_pong_V_ce1 = grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_ce1;
    end else begin
        local_A_pong_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((arb_2_reg_91 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        local_A_pong_V_we1 = grp_A_IO_L2_in_inter_trans_boundary_fu_111_local_A_V_we1;
    end else begin
        local_A_pong_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln270_fu_127_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln271_fu_139_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln272_fu_151_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_A_IO_L2_in_intra_trans_fu_103_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state5_on_subcall_done = (((arb_2_reg_91 == 1'd1) & (grp_A_IO_L2_in_intra_trans_fu_103_ap_done == 1'b0)) | ((arb_2_reg_91 == 1'd0) & (grp_A_IO_L2_in_intra_trans_fu_103_ap_done == 1'b0)) | ((arb_2_reg_91 == 1'd0) & (grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_done == 1'b0)) | ((arb_2_reg_91 == 1'd1) & (grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_done == 1'b0)));
end

assign ap_phi_mux_arb_2_phi_fu_95_p4 = arb_2_reg_91;

assign ap_ready = internal_ap_ready;

assign c0_V_fu_133_p2 = (p_016_0_reg_58 + 3'd1);

assign c1_V_fu_145_p2 = (p_047_0_reg_69 + 3'd1);

assign c2_V_fu_157_p2 = (p_060_0_reg_80 + 3'd1);

assign fifo_A_local_out_V_V_din = grp_A_IO_L2_in_intra_trans_fu_103_fifo_A_local_out_V_V_din;

assign grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_start = grp_A_IO_L2_in_inter_trans_boundary_fu_111_ap_start_reg;

assign grp_A_IO_L2_in_intra_trans_fu_103_ap_start = grp_A_IO_L2_in_intra_trans_fu_103_ap_start_reg;

assign icmp_ln270_fu_127_p2 = ((p_016_0_reg_58 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln271_fu_139_p2 = ((p_047_0_reg_69 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln272_fu_151_p2 = ((p_060_0_reg_80 == 3'd4) ? 1'b1 : 1'b0);

assign start_out = real_start;

assign xor_ln316_fu_163_p2 = (arb_2_reg_91 ^ 1'd1);

endmodule //A_IO_L2_in_boundary
