-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity C_drain_IO_L1_out is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    fifo_C_drain_in_V_V_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    fifo_C_drain_in_V_V_empty_n : IN STD_LOGIC;
    fifo_C_drain_in_V_V_read : OUT STD_LOGIC;
    fifo_C_drain_out_V_V_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    fifo_C_drain_out_V_V_full_n : IN STD_LOGIC;
    fifo_C_drain_out_V_V_write : OUT STD_LOGIC;
    fifo_C_drain_local_in_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    fifo_C_drain_local_in_V_empty_n : IN STD_LOGIC;
    fifo_C_drain_local_in_V_read : OUT STD_LOGIC );
end;


architecture behav of C_drain_IO_L1_out is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_pp2_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal fifo_C_drain_in_V_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal icmp_ln899_reg_607 : STD_LOGIC_VECTOR (0 downto 0);
    signal fifo_C_drain_out_V_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp2_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp2_stage0 : signal is "none";
    signal ap_enable_reg_pp2_iter1 : STD_LOGIC := '0';
    signal ap_block_pp2_stage0 : BOOLEAN;
    signal icmp_ln885_reg_616 : STD_LOGIC_VECTOR (0 downto 0);
    signal fifo_C_drain_local_in_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln849_reg_565 : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_reg_163 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_062_0_i_reg_174 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_076_0_i_reg_185 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten13_reg_259 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten6_reg_270 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_044_0_i_reg_281 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_068_0_i_reg_292 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln953_fu_303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln953_fu_309_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln953_reg_560 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln849_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln849_fu_321_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal select_ln1371_3_fu_347_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln1371_3_reg_574 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln1371_fu_363_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln1371_reg_579 : STD_LOGIC_VECTOR (1 downto 0);
    signal local_C_V_addr_reg_583 : STD_LOGIC_VECTOR (3 downto 0);
    signal c7_V_fu_380_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln882_fu_453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal c4_V_fu_459_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal c4_V_reg_598 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln879_fu_465_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln899_fu_471_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state7_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state8_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal add_ln899_fu_477_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal icmp_ln885_fu_483_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state10_pp2_stage0_iter0 : BOOLEAN;
    signal ap_block_state11_pp2_stage0_iter1 : BOOLEAN;
    signal ap_block_pp2_stage0_11001 : BOOLEAN;
    signal add_ln885_fu_489_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_enable_reg_pp2_iter0 : STD_LOGIC := '0';
    signal select_ln544_4_fu_515_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln544_4_reg_625 : STD_LOGIC_VECTOR (3 downto 0);
    signal c6_V_1_fu_550_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state7 : STD_LOGIC;
    signal ap_block_pp2_stage0_subdone : BOOLEAN;
    signal ap_condition_pp2_exit_iter0_state10 : STD_LOGIC;
    signal local_C_V_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal local_C_V_ce0 : STD_LOGIC;
    signal local_C_V_q0 : STD_LOGIC_VECTOR (127 downto 0);
    signal local_C_V_ce1 : STD_LOGIC;
    signal local_C_V_we1 : STD_LOGIC;
    signal local_C_V_d1 : STD_LOGIC_VECTOR (127 downto 0);
    signal indvar_flatten20_reg_152 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_p_062_0_i_phi_fu_178_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_mux_v1_V_phi_fu_199_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_split_0_V_6_fu_432_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_v1_V_reg_196 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_v2_V_14_phi_fu_212_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_v2_V_14_reg_209 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_v2_V_13_phi_fu_225_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_v2_V_13_reg_222 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_v2_V_phi_fu_238_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_split_0_V_fu_386_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_v2_V_reg_235 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_075_0_i_reg_248 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_phi_mux_p_044_0_i_phi_fu_285_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln321_fu_375_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln321_6_fu_545_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp1_stage0_01001 : BOOLEAN;
    signal ap_block_pp2_stage0_01001 : BOOLEAN;
    signal icmp_ln851_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal c6_V_fu_327_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln1371_fu_339_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_355_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_367_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln887_fu_501_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal c5_V_fu_495_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_523_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln544_fu_507_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln321_5_fu_535_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln887_fu_531_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln321_fu_539_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;
    signal ap_idle_pp2 : STD_LOGIC;
    signal ap_enable_pp2 : STD_LOGIC;

    component C_drain_IO_L1_out_boundary_wrapper135_local_C_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (127 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (127 downto 0) );
    end component;



begin
    local_C_V_U : component C_drain_IO_L1_out_boundary_wrapper135_local_C_V
    generic map (
        DataWidth => 128,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => local_C_V_address0,
        ce0 => local_C_V_ce0,
        q0 => local_C_V_q0,
        address1 => local_C_V_addr_reg_583,
        ce1 => local_C_V_ce1,
        we1 => local_C_V_we1,
        d1 => local_C_V_d1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((icmp_ln953_fu_303_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state3);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((icmp_ln953_fu_303_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state7))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif (((icmp_ln879_fu_465_p2 = ap_const_lv1_0) and (icmp_ln882_fu_453_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state7))) then 
                    ap_enable_reg_pp1_iter1 <= (ap_const_logic_1 xor ap_condition_pp1_exit_iter0_state7);
                elsif ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                elsif (((icmp_ln879_fu_465_p2 = ap_const_lv1_0) and (icmp_ln882_fu_453_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_const_logic_1 = ap_condition_pp2_exit_iter0_state10))) then 
                    ap_enable_reg_pp2_iter0 <= ap_const_logic_0;
                elsif (((icmp_ln882_fu_453_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln879_fu_465_p2 = ap_const_lv1_1))) then 
                    ap_enable_reg_pp2_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp2_exit_iter0_state10))) then 
                    ap_enable_reg_pp2_iter1 <= (ap_const_logic_1 xor ap_condition_pp2_exit_iter0_state10);
                elsif ((ap_const_boolean_0 = ap_block_pp2_stage0_subdone)) then 
                    ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
                elsif (((icmp_ln882_fu_453_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln879_fu_465_p2 = ap_const_lv1_1))) then 
                    ap_enable_reg_pp2_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten13_reg_259_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln879_fu_465_p2 = ap_const_lv1_0) and (icmp_ln882_fu_453_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                indvar_flatten13_reg_259 <= ap_const_lv5_0;
            elsif (((icmp_ln899_fu_471_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
                indvar_flatten13_reg_259 <= add_ln899_fu_477_p2;
            end if; 
        end if;
    end process;

    indvar_flatten20_reg_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln882_fu_453_p2 = ap_const_lv1_1))) then 
                indvar_flatten20_reg_152 <= add_ln953_reg_560;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten20_reg_152 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    indvar_flatten6_reg_270_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln882_fu_453_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln879_fu_465_p2 = ap_const_lv1_1))) then 
                indvar_flatten6_reg_270 <= ap_const_lv5_0;
            elsif (((icmp_ln885_fu_483_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp2_stage0_11001))) then 
                indvar_flatten6_reg_270 <= add_ln885_fu_489_p2;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_163_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln849_fu_315_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten_reg_163 <= add_ln849_fu_321_p2;
            elsif (((icmp_ln953_fu_303_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                indvar_flatten_reg_163 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    p_044_0_i_reg_281_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln882_fu_453_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln879_fu_465_p2 = ap_const_lv1_1))) then 
                p_044_0_i_reg_281 <= ap_const_lv4_0;
            elsif (((icmp_ln885_reg_616 = ap_const_lv1_0) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_const_boolean_0 = ap_block_pp2_stage0_11001))) then 
                p_044_0_i_reg_281 <= select_ln544_4_reg_625;
            end if; 
        end if;
    end process;

    p_062_0_i_reg_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln849_reg_565 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                p_062_0_i_reg_174 <= select_ln1371_3_reg_574;
            elsif (((icmp_ln953_fu_303_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                p_062_0_i_reg_174 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    p_068_0_i_reg_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln882_fu_453_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln879_fu_465_p2 = ap_const_lv1_1))) then 
                p_068_0_i_reg_292 <= ap_const_lv2_0;
            elsif (((icmp_ln885_fu_483_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp2_stage0_11001))) then 
                p_068_0_i_reg_292 <= c6_V_1_fu_550_p2;
            end if; 
        end if;
    end process;

    p_075_0_i_reg_248_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                p_075_0_i_reg_248 <= ap_const_lv2_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                p_075_0_i_reg_248 <= c4_V_reg_598;
            end if; 
        end if;
    end process;

    p_076_0_i_reg_185_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln849_fu_315_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                p_076_0_i_reg_185 <= c7_V_fu_380_p2;
            elsif (((icmp_ln953_fu_303_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                p_076_0_i_reg_185 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln953_reg_560 <= add_ln953_fu_309_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                c4_V_reg_598 <= c4_V_fu_459_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln849_reg_565 <= icmp_ln849_fu_315_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_const_boolean_0 = ap_block_pp2_stage0_11001))) then
                icmp_ln885_reg_616 <= icmp_ln885_fu_483_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                icmp_ln899_reg_607 <= icmp_ln899_fu_471_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln849_fu_315_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                local_C_V_addr_reg_583 <= zext_ln321_fu_375_p1(4 - 1 downto 0);
                trunc_ln1371_reg_579 <= trunc_ln1371_fu_363_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln849_fu_315_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                select_ln1371_3_reg_574 <= select_ln1371_3_fu_347_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln885_fu_483_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp2_stage0_11001))) then
                select_ln544_4_reg_625 <= select_ln544_4_fu_515_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln953_fu_303_p2, ap_CS_fsm_state2, icmp_ln849_fu_315_p2, ap_enable_reg_pp0_iter0, icmp_ln882_fu_453_p2, ap_CS_fsm_state6, icmp_ln879_fu_465_p2, icmp_ln899_fu_471_p2, ap_enable_reg_pp1_iter0, icmp_ln885_fu_483_p2, ap_enable_reg_pp2_iter0, ap_block_pp0_stage0_subdone, ap_block_pp1_stage0_subdone, ap_block_pp2_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln953_fu_303_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln849_fu_315_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln849_fu_315_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln882_fu_453_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((icmp_ln882_fu_453_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln879_fu_465_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln899_fu_471_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln899_fu_471_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_pp2_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (icmp_ln885_fu_483_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (icmp_ln885_fu_483_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln321_fu_539_p2 <= std_logic_vector(unsigned(zext_ln321_5_fu_535_p1) + unsigned(zext_ln887_fu_531_p1));
    add_ln849_fu_321_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_163) + unsigned(ap_const_lv7_1));
    add_ln885_fu_489_p2 <= std_logic_vector(unsigned(indvar_flatten6_reg_270) + unsigned(ap_const_lv5_1));
    add_ln899_fu_477_p2 <= std_logic_vector(unsigned(indvar_flatten13_reg_259) + unsigned(ap_const_lv5_1));
    add_ln953_fu_309_p2 <= std_logic_vector(unsigned(indvar_flatten20_reg_152) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(5);
    ap_CS_fsm_pp2_stage0 <= ap_CS_fsm(7);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);
    ap_CS_fsm_state6 <= ap_CS_fsm(4);
    ap_CS_fsm_state9 <= ap_CS_fsm(6);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(fifo_C_drain_local_in_V_empty_n, ap_enable_reg_pp0_iter1, icmp_ln849_reg_565)
    begin
                ap_block_pp0_stage0_11001 <= ((icmp_ln849_reg_565 = ap_const_lv1_0) and (fifo_C_drain_local_in_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(fifo_C_drain_local_in_V_empty_n, ap_enable_reg_pp0_iter1, icmp_ln849_reg_565)
    begin
                ap_block_pp0_stage0_subdone <= ((icmp_ln849_reg_565 = ap_const_lv1_0) and (fifo_C_drain_local_in_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp1_stage0_01001_assign_proc : process(fifo_C_drain_in_V_V_empty_n, fifo_C_drain_out_V_V_full_n, ap_enable_reg_pp1_iter1, icmp_ln899_reg_607)
    begin
                ap_block_pp1_stage0_01001 <= ((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (((icmp_ln899_reg_607 = ap_const_lv1_0) and (fifo_C_drain_out_V_V_full_n = ap_const_logic_0)) or ((icmp_ln899_reg_607 = ap_const_lv1_0) and (fifo_C_drain_in_V_V_empty_n = ap_const_logic_0))));
    end process;


    ap_block_pp1_stage0_11001_assign_proc : process(fifo_C_drain_in_V_V_empty_n, fifo_C_drain_out_V_V_full_n, ap_enable_reg_pp1_iter1, icmp_ln899_reg_607)
    begin
                ap_block_pp1_stage0_11001 <= ((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (((icmp_ln899_reg_607 = ap_const_lv1_0) and (fifo_C_drain_out_V_V_full_n = ap_const_logic_0)) or ((icmp_ln899_reg_607 = ap_const_lv1_0) and (fifo_C_drain_in_V_V_empty_n = ap_const_logic_0))));
    end process;


    ap_block_pp1_stage0_subdone_assign_proc : process(fifo_C_drain_in_V_V_empty_n, fifo_C_drain_out_V_V_full_n, ap_enable_reg_pp1_iter1, icmp_ln899_reg_607)
    begin
                ap_block_pp1_stage0_subdone <= ((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (((icmp_ln899_reg_607 = ap_const_lv1_0) and (fifo_C_drain_out_V_V_full_n = ap_const_logic_0)) or ((icmp_ln899_reg_607 = ap_const_lv1_0) and (fifo_C_drain_in_V_V_empty_n = ap_const_logic_0))));
    end process;

        ap_block_pp2_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp2_stage0_01001_assign_proc : process(fifo_C_drain_out_V_V_full_n, ap_enable_reg_pp2_iter1, icmp_ln885_reg_616)
    begin
                ap_block_pp2_stage0_01001 <= ((icmp_ln885_reg_616 = ap_const_lv1_0) and (fifo_C_drain_out_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp2_stage0_11001_assign_proc : process(fifo_C_drain_out_V_V_full_n, ap_enable_reg_pp2_iter1, icmp_ln885_reg_616)
    begin
                ap_block_pp2_stage0_11001 <= ((icmp_ln885_reg_616 = ap_const_lv1_0) and (fifo_C_drain_out_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp2_stage0_subdone_assign_proc : process(fifo_C_drain_out_V_V_full_n, ap_enable_reg_pp2_iter1, icmp_ln885_reg_616)
    begin
                ap_block_pp2_stage0_subdone <= ((icmp_ln885_reg_616 = ap_const_lv1_0) and (fifo_C_drain_out_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1));
    end process;

        ap_block_state10_pp2_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state11_pp2_stage0_iter1_assign_proc : process(fifo_C_drain_out_V_V_full_n, icmp_ln885_reg_616)
    begin
                ap_block_state11_pp2_stage0_iter1 <= ((icmp_ln885_reg_616 = ap_const_lv1_0) and (fifo_C_drain_out_V_V_full_n = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter1_assign_proc : process(fifo_C_drain_local_in_V_empty_n, icmp_ln849_reg_565)
    begin
                ap_block_state4_pp0_stage0_iter1 <= ((icmp_ln849_reg_565 = ap_const_lv1_0) and (fifo_C_drain_local_in_V_empty_n = ap_const_logic_0));
    end process;

        ap_block_state7_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_pp1_stage0_iter1_assign_proc : process(fifo_C_drain_in_V_V_empty_n, fifo_C_drain_out_V_V_full_n, icmp_ln899_reg_607)
    begin
                ap_block_state8_pp1_stage0_iter1 <= (((icmp_ln899_reg_607 = ap_const_lv1_0) and (fifo_C_drain_out_V_V_full_n = ap_const_logic_0)) or ((icmp_ln899_reg_607 = ap_const_lv1_0) and (fifo_C_drain_in_V_V_empty_n = ap_const_logic_0)));
    end process;


    ap_condition_pp0_exit_iter0_state3_assign_proc : process(icmp_ln849_fu_315_p2)
    begin
        if ((icmp_ln849_fu_315_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp1_exit_iter0_state7_assign_proc : process(icmp_ln899_fu_471_p2)
    begin
        if ((icmp_ln899_fu_471_p2 = ap_const_lv1_1)) then 
            ap_condition_pp1_exit_iter0_state7 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state7 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp2_exit_iter0_state10_assign_proc : process(icmp_ln885_fu_483_p2)
    begin
        if ((icmp_ln885_fu_483_p2 = ap_const_lv1_1)) then 
            ap_condition_pp2_exit_iter0_state10 <= ap_const_logic_1;
        else 
            ap_condition_pp2_exit_iter0_state10 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln953_fu_303_p2, ap_CS_fsm_state2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln953_fu_303_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);
    ap_enable_pp2 <= (ap_idle_pp2 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter0)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp2_assign_proc : process(ap_enable_reg_pp2_iter1, ap_enable_reg_pp2_iter0)
    begin
        if (((ap_enable_reg_pp2_iter1 = ap_const_logic_0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_0))) then 
            ap_idle_pp2 <= ap_const_logic_1;
        else 
            ap_idle_pp2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_p_044_0_i_phi_fu_285_p4_assign_proc : process(ap_CS_fsm_pp2_stage0, ap_enable_reg_pp2_iter1, ap_block_pp2_stage0, icmp_ln885_reg_616, p_044_0_i_reg_281, select_ln544_4_reg_625)
    begin
        if (((ap_const_boolean_0 = ap_block_pp2_stage0) and (icmp_ln885_reg_616 = ap_const_lv1_0) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
            ap_phi_mux_p_044_0_i_phi_fu_285_p4 <= select_ln544_4_reg_625;
        else 
            ap_phi_mux_p_044_0_i_phi_fu_285_p4 <= p_044_0_i_reg_281;
        end if; 
    end process;


    ap_phi_mux_p_062_0_i_phi_fu_178_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln849_reg_565, p_062_0_i_reg_174, select_ln1371_3_reg_574)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln849_reg_565 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_p_062_0_i_phi_fu_178_p4 <= select_ln1371_3_reg_574;
        else 
            ap_phi_mux_p_062_0_i_phi_fu_178_p4 <= p_062_0_i_reg_174;
        end if; 
    end process;


    ap_phi_mux_v1_V_phi_fu_199_p8_assign_proc : process(icmp_ln849_reg_565, trunc_ln1371_reg_579, local_C_V_q0, data_split_0_V_6_fu_432_p1, ap_phi_reg_pp0_iter1_v1_V_reg_196)
    begin
        if ((((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_0)) or ((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_1)) or ((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_2)))) then 
            ap_phi_mux_v1_V_phi_fu_199_p8 <= local_C_V_q0(127 downto 96);
        elsif (((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_3))) then 
            ap_phi_mux_v1_V_phi_fu_199_p8 <= data_split_0_V_6_fu_432_p1;
        else 
            ap_phi_mux_v1_V_phi_fu_199_p8 <= ap_phi_reg_pp0_iter1_v1_V_reg_196;
        end if; 
    end process;


    ap_phi_mux_v2_V_13_phi_fu_225_p8_assign_proc : process(icmp_ln849_reg_565, trunc_ln1371_reg_579, local_C_V_q0, data_split_0_V_6_fu_432_p1, ap_phi_reg_pp0_iter1_v2_V_13_reg_222)
    begin
        if (((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_1))) then 
            ap_phi_mux_v2_V_13_phi_fu_225_p8 <= data_split_0_V_6_fu_432_p1;
        elsif ((((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_0)) or ((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_2)) or ((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_3)))) then 
            ap_phi_mux_v2_V_13_phi_fu_225_p8 <= local_C_V_q0(63 downto 32);
        else 
            ap_phi_mux_v2_V_13_phi_fu_225_p8 <= ap_phi_reg_pp0_iter1_v2_V_13_reg_222;
        end if; 
    end process;


    ap_phi_mux_v2_V_14_phi_fu_212_p8_assign_proc : process(icmp_ln849_reg_565, trunc_ln1371_reg_579, local_C_V_q0, data_split_0_V_6_fu_432_p1, ap_phi_reg_pp0_iter1_v2_V_14_reg_209)
    begin
        if (((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_2))) then 
            ap_phi_mux_v2_V_14_phi_fu_212_p8 <= data_split_0_V_6_fu_432_p1;
        elsif ((((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_0)) or ((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_1)) or ((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_3)))) then 
            ap_phi_mux_v2_V_14_phi_fu_212_p8 <= local_C_V_q0(95 downto 64);
        else 
            ap_phi_mux_v2_V_14_phi_fu_212_p8 <= ap_phi_reg_pp0_iter1_v2_V_14_reg_209;
        end if; 
    end process;


    ap_phi_mux_v2_V_phi_fu_238_p8_assign_proc : process(icmp_ln849_reg_565, trunc_ln1371_reg_579, data_split_0_V_6_fu_432_p1, data_split_0_V_fu_386_p1, ap_phi_reg_pp0_iter1_v2_V_reg_235)
    begin
        if (((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_0))) then 
            ap_phi_mux_v2_V_phi_fu_238_p8 <= data_split_0_V_6_fu_432_p1;
        elsif ((((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_1)) or ((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_2)) or ((icmp_ln849_reg_565 = ap_const_lv1_0) and (trunc_ln1371_reg_579 = ap_const_lv2_3)))) then 
            ap_phi_mux_v2_V_phi_fu_238_p8 <= data_split_0_V_fu_386_p1;
        else 
            ap_phi_mux_v2_V_phi_fu_238_p8 <= ap_phi_reg_pp0_iter1_v2_V_reg_235;
        end if; 
    end process;

    ap_phi_reg_pp0_iter1_v1_V_reg_196 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_v2_V_13_reg_222 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_v2_V_14_reg_209 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_v2_V_reg_235 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_ready_assign_proc : process(icmp_ln953_fu_303_p2, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln953_fu_303_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    c4_V_fu_459_p2 <= std_logic_vector(unsigned(p_075_0_i_reg_248) + unsigned(ap_const_lv2_1));
    c5_V_fu_495_p2 <= std_logic_vector(unsigned(ap_phi_mux_p_044_0_i_phi_fu_285_p4) + unsigned(ap_const_lv4_1));
    c6_V_1_fu_550_p2 <= std_logic_vector(unsigned(select_ln544_fu_507_p3) + unsigned(ap_const_lv2_1));
    c6_V_fu_327_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(ap_phi_mux_p_062_0_i_phi_fu_178_p4));
    c7_V_fu_380_p2 <= std_logic_vector(unsigned(select_ln1371_fu_339_p3) + unsigned(ap_const_lv4_1));
    data_split_0_V_6_fu_432_p1 <= fifo_C_drain_local_in_V_dout;
    data_split_0_V_fu_386_p1 <= local_C_V_q0(32 - 1 downto 0);

    fifo_C_drain_in_V_V_blk_n_assign_proc : process(fifo_C_drain_in_V_V_empty_n, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln899_reg_607)
    begin
        if (((icmp_ln899_reg_607 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            fifo_C_drain_in_V_V_blk_n <= fifo_C_drain_in_V_V_empty_n;
        else 
            fifo_C_drain_in_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    fifo_C_drain_in_V_V_read_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln899_reg_607, ap_block_pp1_stage0_11001)
    begin
        if (((icmp_ln899_reg_607 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
            fifo_C_drain_in_V_V_read <= ap_const_logic_1;
        else 
            fifo_C_drain_in_V_V_read <= ap_const_logic_0;
        end if; 
    end process;


    fifo_C_drain_local_in_V_blk_n_assign_proc : process(fifo_C_drain_local_in_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln849_reg_565)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln849_reg_565 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fifo_C_drain_local_in_V_blk_n <= fifo_C_drain_local_in_V_empty_n;
        else 
            fifo_C_drain_local_in_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    fifo_C_drain_local_in_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln849_reg_565, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln849_reg_565 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            fifo_C_drain_local_in_V_read <= ap_const_logic_1;
        else 
            fifo_C_drain_local_in_V_read <= ap_const_logic_0;
        end if; 
    end process;


    fifo_C_drain_out_V_V_blk_n_assign_proc : process(fifo_C_drain_out_V_V_full_n, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln899_reg_607, ap_CS_fsm_pp2_stage0, ap_enable_reg_pp2_iter1, ap_block_pp2_stage0, icmp_ln885_reg_616)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp2_stage0) and (icmp_ln885_reg_616 = ap_const_lv1_0) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0)) or ((icmp_ln899_reg_607 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then 
            fifo_C_drain_out_V_V_blk_n <= fifo_C_drain_out_V_V_full_n;
        else 
            fifo_C_drain_out_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    fifo_C_drain_out_V_V_din_assign_proc : process(fifo_C_drain_in_V_V_dout, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln899_reg_607, ap_CS_fsm_pp2_stage0, ap_enable_reg_pp2_iter1, icmp_ln885_reg_616, local_C_V_q0, ap_block_pp1_stage0_01001, ap_block_pp2_stage0_01001)
    begin
        if (((icmp_ln885_reg_616 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp2_stage0_01001) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
            fifo_C_drain_out_V_V_din <= local_C_V_q0;
        elsif (((icmp_ln899_reg_607 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_01001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            fifo_C_drain_out_V_V_din <= fifo_C_drain_in_V_V_dout;
        else 
            fifo_C_drain_out_V_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    fifo_C_drain_out_V_V_write_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln899_reg_607, ap_CS_fsm_pp2_stage0, ap_enable_reg_pp2_iter1, icmp_ln885_reg_616, ap_block_pp1_stage0_11001, ap_block_pp2_stage0_11001)
    begin
        if ((((icmp_ln885_reg_616 = ap_const_lv1_0) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_const_boolean_0 = ap_block_pp2_stage0_11001)) or ((icmp_ln899_reg_607 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)))) then 
            fifo_C_drain_out_V_V_write <= ap_const_logic_1;
        else 
            fifo_C_drain_out_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln849_fu_315_p2 <= "1" when (indvar_flatten_reg_163 = ap_const_lv7_40) else "0";
    icmp_ln851_fu_333_p2 <= "1" when (p_076_0_i_reg_185 = ap_const_lv4_8) else "0";
    icmp_ln879_fu_465_p2 <= "1" when (p_075_0_i_reg_248 = ap_const_lv2_0) else "0";
    icmp_ln882_fu_453_p2 <= "1" when (p_075_0_i_reg_248 = ap_const_lv2_2) else "0";
    icmp_ln885_fu_483_p2 <= "1" when (indvar_flatten6_reg_270 = ap_const_lv5_10) else "0";
    icmp_ln887_fu_501_p2 <= "1" when (p_068_0_i_reg_292 = ap_const_lv2_2) else "0";
    icmp_ln899_fu_471_p2 <= "1" when (indvar_flatten13_reg_259 = ap_const_lv5_10) else "0";
    icmp_ln953_fu_303_p2 <= "1" when (indvar_flatten20_reg_152 = ap_const_lv5_10) else "0";

    local_C_V_address0_assign_proc : process(ap_CS_fsm_pp2_stage0, ap_block_pp2_stage0, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp2_iter0, zext_ln321_fu_375_p1, zext_ln321_6_fu_545_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp2_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1))) then 
            local_C_V_address0 <= zext_ln321_6_fu_545_p1(4 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            local_C_V_address0 <= zext_ln321_fu_375_p1(4 - 1 downto 0);
        else 
            local_C_V_address0 <= "XXXX";
        end if; 
    end process;


    local_C_V_ce0_assign_proc : process(ap_CS_fsm_pp2_stage0, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0, ap_block_pp2_stage0_11001, ap_enable_reg_pp2_iter0)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp2_stage0_11001)))) then 
            local_C_V_ce0 <= ap_const_logic_1;
        else 
            local_C_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    local_C_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_C_V_ce1 <= ap_const_logic_1;
        else 
            local_C_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_C_V_d1 <= (((ap_phi_mux_v1_V_phi_fu_199_p8 & ap_phi_mux_v2_V_14_phi_fu_212_p8) & ap_phi_mux_v2_V_13_phi_fu_225_p8) & ap_phi_mux_v2_V_phi_fu_238_p8);

    local_C_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln849_reg_565, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln849_reg_565 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_C_V_we1 <= ap_const_logic_1;
        else 
            local_C_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln1371_3_fu_347_p3 <= 
        c6_V_fu_327_p2 when (icmp_ln851_fu_333_p2(0) = '1') else 
        ap_phi_mux_p_062_0_i_phi_fu_178_p4;
    select_ln1371_fu_339_p3 <= 
        ap_const_lv4_0 when (icmp_ln851_fu_333_p2(0) = '1') else 
        p_076_0_i_reg_185;
    select_ln544_4_fu_515_p3 <= 
        c5_V_fu_495_p2 when (icmp_ln887_fu_501_p2(0) = '1') else 
        ap_phi_mux_p_044_0_i_phi_fu_285_p4;
    select_ln544_fu_507_p3 <= 
        ap_const_lv2_0 when (icmp_ln887_fu_501_p2(0) = '1') else 
        p_068_0_i_reg_292;
    tmp_2_fu_367_p3 <= (select_ln1371_fu_339_p3 & tmp_fu_355_p3);
    tmp_3_fu_523_p3 <= (select_ln544_4_fu_515_p3 & ap_const_lv1_0);
    tmp_fu_355_p3 <= select_ln1371_3_fu_347_p3(2 downto 2);
    trunc_ln1371_fu_363_p1 <= select_ln1371_3_fu_347_p3(2 - 1 downto 0);
    zext_ln321_5_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln544_fu_507_p3),6));
    zext_ln321_6_fu_545_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln321_fu_539_p2),64));
    zext_ln321_fu_375_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_367_p3),64));
    zext_ln887_fu_531_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_523_p3),6));
end behav;
